### ISSUE TITLE
Permission denied when trying to clone the repositories

### ISSUE THREAD

**Issue by bbn-github** [AnalyticsMediaGroup/strongbolt#1]
git clone git@github.com:AnalyticsMediaGroup/grant.git
Cloning into 'grant'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bbn-github** [comment]
Obviously changing it to the https path works fine...

gem 'grant', git: "https://github.com/AnalyticsMediaGroup/grant.git"
gem 'strongbolt', git: "https://github.com/AnalyticsMediaGroup/strongbolt.git"

**Comment by tobithiel** [comment]
The Readme contained older instructions unfortunately. I've updated the instructions to use the Rubygems version.
If someone needs the latest master changes, using https://github.com/AnalyticsMediaGroup/strongbolt.git should be fine, I think.
Let me know if that resolves your issues.
