### ISSUE TITLE
ActiveAdmin integration

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#10]
Is there any ideas on how to get strongbolt works with ActiveAdmin ? usually, AA uses an adapters to work with cancan or pundit, but strongbolt in the other hand, needs to know which controller like the dashboard on active admin to stop authorizing it as it contains no models, also provisioning AA controllers to `config.skip_controller_authorization_for ` is hard as AA doesn't put any explicit controllers in the route file.
so is there any work flow that I should consider ?

**Comment by tobithiel** [comment]
ActiveAdmin seems to provide the possibility to implement custom [Authorization Adapters](http://activeadmin.info/docs/13-authorization-adapter.html). Strongbolt provides the method `can?(action, instance)` on the user class which could be used to implement such an adapter. Action is one of these: `find create update destroy`, Instance is the ActiveRecord model instance the user wants to access or modify.

We're not using ActiveAdmin, so I don't see us implementing this anytime soon. But we'd be happy to accept a pull request if you choose to go down that road and implement the adapter. It seems like it would be a fairly thin layer between AA and Strongbolt.

**Comment by ahmgeek** [comment]
I'd love to send PRs in the feature, I also will be more than happy to see this Gem evolve.

**Comment by basco-johnkevin** [comment]
+1. We're planning to use strongbolt + active admin.
