### ISSUE TITLE
Models with :HasAndBelongsToMany

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#11]
Models that have `HABTM` relations got misleading names in the strongbolt initializer
```
 config.models = 'ActiveRecord::SessionStore::Session', 'Group', 'HABTM_Assets', 'School', 'Grade',
 'Stream', 'User', 'ActiveAdmin::Comment', 'Addation', 'Asset', 'HABTM_Groups', 'HABTM_Lessons', 
'Assignment', 'HABTM_Contents', 'AssignmentAnswer', 'AssignmentScoresheet', 'Category', 'Comment', 
'Content', 'HABTM_Quizzes', 'Lesson', 'HABTM_RelatedResources', 'License', 'Membership', 
'Notification', 'Organization', 'Permission', 'Post', 'Quiz', 'HABTM_Contents', 'Role', 'Scoresheet',
 'Subject', 'Document', 'Audio', 'Image', 'Video', 'Attachment', 'Question'
```
notice: `HABTM_Groups` got `HABTM` before the model name

**Comment by tobithiel** [comment]
Strongbolt just uses whatever the model is actually named. HABTM_... is the default name from ActiveRecord for these associations: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/builder/has_and_belongs_to_many.rb#L84

If you want to control the name, you can always use normal has_many associations and pick whatever name you'd like.
Adding functionality to override model names in Strongbolt makes it unnecessarily complicated and hard to trace back what is actually the underlying model, I think.
