### ISSUE TITLE
Roles parents

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#13]
what is the benefits of having a parent in the roles creation ?

**Comment by tobithiel** [comment]
We're using them like this for example:
- Role 1: `Access X`; read-only access
- Role 2: `Manage X` inherits Role 1; read-write access
Adding a new capability in Role 1 will automatically add it to Role 2 as well. This means the Manage Role has automatically all the read access it needs and we can add more capabilities as we need them.

**Comment by ahmgeek** [comment]
Thanks, and what's the use of `lft`, `rgt` as I couldn't relate them.

**Comment by tobithiel** [comment]
For details about `lft` and `rgt` look here: https://github.com/collectiveidea/awesome_nested_set
