### ISSUE TITLE
Still getting what already in the user_groups_users

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#16]
The drop down still gets what already in the table : [Here](https://github.com/AnalyticsMediaGroup/strongbolt/blob/master/app/controllers/strongbolt/user_groups_controller.rb#L10-L13)

**Comment by tobithiel** [comment]
I don't understand what you're saying. Can you elaborate a bit?

**Comment by ahmgeek** [comment]
this route `strongbolt/user_groups/[id]` have a drop-down list that contains the users, regards the line in the upper comment, it should only contains the unique users that not in the user_groups_users table.
but if a user already in that group, it got displayed in the drop-down list again. [this line](https://github.com/AnalyticsMediaGroup/strongbolt/blob/master/app/controllers/strongbolt/user_groups_users_controller.rb#L10) is the only line that prevent a user to be in the same group twice.

**Comment by tobithiel** [comment]
I just looked into this and couldn't reproduce it in our example app. It correctly filters out users that are already in the user group.
The drop down only shows users that are not yet in the group.

Are you sure this is happening in Strongbolt code? Can you give us more information?
