### ISSUE TITLE
rake task strongbolt:seed empties my user database and does nothing else

### ISSUE THREAD

**Issue by onkeld** [AnalyticsMediaGroup/strongbolt#2]
I have a rails app using Devise for authentication.
During Setup I create one User to start off by using rake db:seed.
The user is present in the database and functions normally (sign in, sign out, authenticate! as per normal Devise behaviour).

After installing Strongbolt as per the README (rails g strongbolt:install && rake db:migrate), I have the Strongbolt database tables as well - however empty.

After running rake strongbolt:seed, all the Strongbolt tables in the Database are still empty, but so is my User table from Devise.
The previously present User is simply gone.

So far, the User model is the only model present in the app.

Any suggestions as to what is happening here?

**Comment by onkeld** [comment]
additional info: I'm using the gem as in the readme via bundle.
also: running rake --tasks doesn't list the strongbolt:seed task at all.

I tried again, using explicit RAILS_ENV=development with the rake and this time it works.
Seems like your task runs on production database by default.

**Comment by onkeld** [comment]
Further:

The rake task does only include permissions for the Strongbolt table, not for my preexisting Users table.
This could be intended, however.

**Comment by onkeld** [comment]
Adding Capabilities for the User model manually in the database works as expected.

Will there be a frontend for managing permissions at some point in the near future?

**Comment by jgrosche** [comment]
The built-in views can be added using the generator named strongbolt:views, the views can then be found in views/strongbolt, unfortunately it looks like no routes are added

**Comment by tobithiel** [comment]
Regarding strongbolt:seed:
I couldn't reproduce what you're describing unfortunately. If you look at the code for the `strongbolt:seed` task in `lib/tasks/strongbolt_tasks.rake`, it doesn't do much, except creating a full access Role & Group, which the existing Users are assigned to. The task doesn't appear in `rake -T` right now, but it should work regardless of that.

Regarding RAILS_ENV:
Strongbolt doesn't mess around with that.

Permissions management frontend:
As mentioned there are some rudimentary views available, although it isn't really well documented. Adding `strongbolt` to your routes.rb will register routes for them.

We'll provide a small example application with Devise + Strongbolt sometime soon to show the usage of most of Strongbolt's features. That should make it easier to get started with it.

**Comment by onkeld** [comment]
Thanks for the tips!
Looks like things are not quite finished in the controller though.
I added the routes and rake routes shows me what's available.
When using the route to strongbolt_index, in the URI /strongbolt, I get the "Unknown Action" Error with "The action 'index' could not be found for StrongboltController".

Seems like you are offering a route to the index action, but forgot to do something with it.
Will be able to work around that for now, but might be good to fix in the future...
I consider this issue as resolved now...
