### ISSUE TITLE
Define attr_accessible for Strongbolt::Capability

### ISSUE THREAD

**Issue by jaydave** [AnalyticsMediaGroup/strongbolt#21]
strongbolt gem fails If I have `config.active_record.whitelist_attributes = true` in my application for mass assignment protection. User may not want to remove that just for this gem. It will be good to have it like this 
```
attr_accessible :model, :require_ownership, :require_tenant_access, :action
```

You can close this issue if it is depended on individual app

**Comment by tobithiel** [comment]
I was looking for that option as I'm not aware of it and it seems that it is from the `protected_attributes` gem, which deprecated it: https://github.com/rails/protected_attributes/blob/master/lib/protected_attributes/railtie.rb
I'd be hesitant to make that change for a deprecated configuration option. Let me know if I missed something and this is still a fully supported configuration. Then I would agree that Strongbolt should support it.

**Comment by jaydave** [comment]
I am not sure about the behavior if we use `strong_parameters` and add protection globally. I will try to check that locally and will update you. Other than that, I agree with you about not making change for deprecated config option.

**Comment by tobithiel** [comment]
Sounds good! Please reopen in case you find out this is still an issue.
