### ISSUE TITLE
Unexpected behavior in certain scenarios

### ISSUE THREAD

**Issue by jaydave** [AnalyticsMediaGroup/strongbolt#22]
I am using example app to play around here
- Boot up the app
- use second user to login which is `user@example.com`
- go to categories and visit edit page
- confirm that you can see `categories/1` and get unauthorized error for `categories/2`
- Now, go to `CategoriesController` and type `exit` in `def edit` to cause error
- visit the page `categories/1 and you will see `:Unauthorized` error
- now remove `exit` from code and revisit that same page
- It will keep displaying `Strongbolt::Unauthorized` untill you restart server

**Comment by tobithiel** [comment]
`user@example.com` doesn't have edit permission for me so I'm already getting unauthorized errors when visiting the edit page.
I tried the `exit` thing on `CategoriesController::show`, but couldn't trigger what you described. Can you try to reproduce this on an unmodified repository or provide more details on what you changed?

**Comment by jaydave** [comment]
I had some changed locally in gem which was causing it to break. Sorry for trouble.
Closing this as it is not the issue.
