### ISSUE TITLE
Rails 5 incompatibility

### ISSUE THREAD

**Issue by FreeApophis** [AnalyticsMediaGroup/strongbolt#23]
I am surprised no one raised the issue yet, but strongbolt 0.3.10 (latest) depends on awesome_nested_set  ~> 3.0.0 and that one wants an active record <5, >=4.0.0

I have seen commit ad1fe230d622ad27c0e0121148575ca6f1dbe095 which solves the problem, but it seems like this one has never been pushed even though the version was pushed to 0.3.10.

I changed the dependecy to git and it works. Would be nice if you could push an updated Gem.

TY

**Comment by tobithiel** [comment]
I pushed a new version 0.3.11 which has that commit. Sorry about the delay in publishing that.

**Comment by FreeApophis** [comment]
Wow that was fast :) ty
