### ISSUE TITLE
The article linked to this library

### ISSUE THREAD

**Issue by nicolas-besnard** [AnalyticsMediaGroup/strongbolt#27]
I found your gem a while ago thanks to a blog article your wrote.

Is there any chance you still have this article online ? Can't find it :(

**Comment by tobithiel** [comment]
Sorry about that, we're in the middle of transferring our website. The article is available here now: https://www-old.amg.tv/blog/strongbolt-why-and-how-we-built-our-own-rails-authorization-framework
