### ISSUE TITLE
Strongbolt doesn't secure itself properly

### ISSUE THREAD

**Issue by onkeld** [AnalyticsMediaGroup/strongbolt#29]
In my App, I used the 'rake strongbolt:seed' command to create a full access user group with permissions to strongbolt and the user model.
My only user is member of that group.
Even when I am not logged in as that user, I still get full access to the strongbolt routes (e.g. http://localhost:3000/strongbolt/user_groups).
Therefore, anybody who knows how to find the mentioned view can alter all of the settings in strongbolt.
This kind of defeats its purpose If I can tailor permissions to my liking even if nobody is logged in.

**Comment by onkeld** [comment]
Checking further, I see that I am able to access the routes and apparently use them.
However, nothing is saved while being not logged in.
In the logfile, I see `No authorization checking because no current user`, which tells me, that strongbolt does recognized we're not logged in.
Wouldn't it be reasonable to throw some sort of error here? 
Or prevent access to the routes altogether by sending the not-user back to the login screen? 
For my own controllers, I achieve that by using Devise's before_filter :authenticate_user! on the controller. If not authenticated (i.e. not logged in), I will see the login screen and nothing else.

**Comment by tobithiel** [comment]
Strongbolt doesn't handle authentication, so you will need to add any authentication checks that you need to these views.
The views are the bare minimum right now, they can be overriden by the application if you want to implement your own. The javascript that handles that view is [here](https://github.com/AnalyticsMediaGroup/strongbolt/blob/master/app/assets/javascripts/strongbolt/role-capabilities.js), if you want to extend it and contribute that back.

**Comment by onkeld** [comment]
Got that, thanks!
Will have a look into this.
Might be necessary for me to implement my own way of handling this anyways after all...
