### ISSUE TITLE
Use of strongbolt_users_tenants table not clear

### ISSUE THREAD

**Issue by jgrosche** [AnalyticsMediaGroup/strongbolt#3]
I've setup a test application and have configured all of the required groups and roles using the built-in views. 

What I'm not clear on is the use of the table **'strongbolt_users_tenants'**, in particular the values of needed for columns **'tenant_id'** and **'type'** nothing appears to write to this table and there is no build-in view.

Can you please give an example of how this table is managed in relation to the tenant setup in the initializer.

Also I think a sample crud application based on some of the scenarios in the brief documentation would go along way to help.

**Comment by jgrosche** [comment]
Ok I figured this out myself, that said the documentation for this library does have a few gaps that need plugging, also the built-in views need updating.

Another issue I found, the skip authorization for devise in the controllers section of the documentation does not work, it cannot find the devise controllers -

config.skip_controller_authorization_for "Devise::SessionsController", "Devise::RegistrationsController"

should be - 

config.skip_controller_authorization_for "Devise::Sessions", "Devise::Registrations"

This is because of the following line in configuration.rb -

[**"#{controller.camelize}Controller"**.constantize.send :skip_controller_authorization](https://github.com/AnalyticsMediaGroup/strongbolt/blob/master/lib/strongbolt/configuration.rb#L87)

Results in the method trying validate a controller named Devise::SessionsControllerController

Other than that this is a great piece of work and thanks for opening it up to the community

**Comment by tobithiel** [comment]
For people looking at this with the same question. If your Tenant is a Client, Stringbolt will define an association on your User class called `clients`. Adding/Removing instances will update the `strongbolt_users_tenants` table. To add a client you would run `myUser.clients << myClient`. To remove all clients, you would run `myUser.clients.clear`. You can interact with it like with any ActiveRecord association.

Thanks for trying out Strongbolt. We'll release a small example application to show how Strongbolt can be used soon.
