### ISSUE TITLE
Strongbolt Controller incomplete

### ISSUE THREAD

**Issue by onkeld** [AnalyticsMediaGroup/strongbolt#4]
To follow up on my last comment in #2, here's the issue for the incomplete controller.

When using the route provided by adding :strongbolt to routes.rb, to strongbolt_index, in the URI /strongbolt, I get the "Unknown Action" Error with "The action 'index' could not be found for StrongboltController".

Looks like the route supports an index action which is not present in the controller.
Also, if the index action was to be implemented, a corresponding view would be needed as well.

**Comment by tobithiel** [comment]
What's the output of `rake routes` in your project?

**Comment by tobithiel** [comment]
I just set up a new Strongbolt application and wasn't able to reproduce that, unfortunately. There is no index route created for me.
We've published an example app which has Strongbolt fully set up, including the routes and views. It is available at https://github.com/AnalyticsMediaGroup/strongbolt_example.
Let me know if that helps.

**Comment by onkeld** [comment]
I added the routes by applying :strongbolt to the resources in my routes.rb.
The routes I'm getting by that is 

 strongbolt_index GET    /strongbolt(.:format)          strongbolt#index
                     POST   /strongbolt(.:format)          strongbolt#create
      new_strongbolt GET    /strongbolt/new(.:format)      strongbolt#new
     edit_strongbolt GET    /strongbolt/:id/edit(.:format) strongbolt#edit
          strongbolt GET    /strongbolt/:id(.:format)      strongbolt#show
                     PATCH  /strongbolt/:id(.:format)      strongbolt#update
                     PUT    /strongbolt/:id(.:format)      strongbolt#update
                     DELETE /strongbolt/:id(.:format)      strongbolt#destroy

When using the provided "index" route I get the mentioned error.

I'll have a look at the demo app...

**Comment by tobithiel** [comment]
I am not sure sure what you mean by

> I added the routes by applying :strongbolt to the resources in my routes.rb.

Could you post the content of your `routes.rb`?

**Comment by tobithiel** [comment]
Please reopen if you're still encountering this issue.
